allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true

ignoredBuiltDependencies:
  - esbuild
  - vue-demi

onlyBuiltDependencies:
  - '@parcel/watcher'
  - sharp
  - workerd
