allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true

ignoredBuiltDependencies:
  - esbuild
  - vue-demi

onlyBuiltDependencies:
  - '@parcel/watcher'
  - sharp
  - workerd

overrides:
  '@vue/compiler-sfc': 3.5.33
  '@vue/server-renderer': 3.5.33
  '@tailwindcss/node': 4.3.0
  '@tailwindcss/postcss': 4.3.0
  '@tailwindcss/vite': 4.3.0
  tailwindcss: 4.3.0
  vue: 3.5.33
